config/routes.rb
Rails.application.routes.draw do

  get 'collaborators/new'

  devise_for :users

  resources :wikis

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges, only: [:new, :create] do
    collection do
      delete :downgrade
    end
  end

  get 'about' => 'welcome#about'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy
  has_many :collab_wikis, through: :collaborators, source: :wiki

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]

  before_save { self.role ||= :standard }

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  validates :user, presence: true

  def possible_collaborators(current_user_id)
    pc_ids = User.ids - users.map(&:id) - [current_user_id]
    User.find(pc_ids)
  end

  def public?
    !private?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Membership - #{current_user.email}",
      amount: @amount
    }
  end

  def create
    @amount = 1500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    current_user.update_attribute(:role, 'premium')

    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def downgrade
    current_user.update_attribute(:role, 'standard')
    redirect_to root_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def new
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new

    @current_collaborators = @wiki.collaborators
    @not_current_collaborators = @wiki.possible_collaborators(current_user.id)  
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])

    @collaborator = Collaborator.new(collaborator_params)
    authorize @collaborator
    if @collaborator.save
      flash[:notice] = "#{@collaborator.user.email} was successfully added a a collaborator."
      redirect_to @wiki
    else
      flash[:notice] = "Collaborator was not added. Please try again."
      redirect_to @wiki
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    @user = @collaborator.user

    if @collaborator.destroy
      flash[:notice] = "Collaborator #{@user.email} is no longer a collaborator on this wiki."
      redirect_to @wiki
    else
      flash.now[:alert] = "An error occurred while deleting that collaborator."
      redirect_to @wiki
    end
  end

  private

  def collaborator_params
    params.require(:collaborator).permit(:wiki_id, :user_id)
  end
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def new
  end

  def create
    current_user.standard!
    current_user.wikis.each do |pub|
      pub.update_attribute(:private, false)
    end

    flash[:notice] = "Your account has been downgraded to a standard account. Your private wikis are now public. You will recieve a $15.00 refund."
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    if current_user.standard?
      @wikis = Wiki.where(private: false)
    else
      @wikis = policy_scope(Wiki)
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @current_collaborators = @wiki.collaborators
    authorize(@wiki)
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<!-- <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %> -->

 <%= form_tag charges_path do %>
 <br>
 <p>Your current membership level is: <strong><%= current_user.role %></strong></p>
   <% if current_user.role == 'standard' %>
     <article>
       <% if flash[:error].present? %>
         <div id="error_explanation">
           <p><%= flash[:error] %></p>
         </div>
       <% end %>
       <label class="amount">
         <span>Upgrade to Premium: $15.00</span>
       </label>
     </article>

     <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
             data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
             data-description="A month's subscription"
             data-amount="1500"
             data-locale="auto"></script>
   <% elsif current_user.role == 'premium' %>
     <%= link_to "Downgrade Account", downgrade_charges_path, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to downgrade your account? All of your private wikis will be made public, and you will have to pay again to upgrade your account later.' } %>
   <% end %>
 <% end %>

app/views/collaborators/new.html.erb
<h1>Add Collaborators</h1>
<%= form_for [@wiki, @collaborator]  do |f| %>

  <div class= 'form-group'>
    <%= f.hidden_field :wiki_id, :value => params[:wiki_id] %>
    <%= f.label "Select new collaborator", class: 'form-label' %>
    <%= f.select 'user_id', options_from_collection_for_select(@not_current_collaborators, 'id', 'email') %>
  </div>

  <div class='form-group'>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="pull-right login">
    <% if user_signed_in? %>
   Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
  </div>
  <ul class="nav nav-tabs">
    <li><%= link_to "Blocipedia", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Wikis", wikis_path %></li>
    <li><%= link_to "Upgrade", new_charge_path %></li> 
  </ul>
  <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  <%= yield %>
 </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by: Eljam</p>

app/views/welcome/index.html.erb
<h1>Blocipedia</h1>
<p>A Bloc Wiki project that anyone can edit.</p>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it works.</li>
      <li>Make a wiki anyone can edit!</li>
    </ul>
  </div>

  <% if @wiki.private == true && (current_user == @wiki.user || current_user.admin?) %>
          <h3> Manage Collaborators </h3>
          <br />
        <%= link_to "Add Collaborator", new_wiki_collaborator_path(wiki_id: @wiki), class: 'btn btn-success' %>
        <br />
          <% if @wiki.collaborators.present? %>

              <% @current_collaborators = @wiki.collaborators %>
              <% wiki_id = @wiki.id %>
              <% @current_collaborators.each do |collaborator| %>
                <tr>
                  <td>
                    <strong> <%= collaborator.user.email %> </strong>
                    <%= button_to "Remove Collaborator", wiki_collaborator_path(@wiki.id, collaborator.id), method: :delete, class: 'btn btn-danger' %>
                  </td>
                </tr>
              <% end %>
            </table>
          <% end %>
        <% end %>
      </div>

  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
      <% if current_user.admin? || current_user.premium? %>
        <%= f.label :private do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
        <%= link_to markdown(wiki.title), wiki %>
        </h4>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/wikis/new.html.erb
    <h1>New Wiki</h1>
    <div class="row">
        <div class="col-md-4">
            <p>Wiki rules</p>
            <ul>
                <li>Upgrade or downgrade.</li>
                <li>Make a wiki anyone can edit!</li>
            </ul>
        </div>
        <div class="col-md-8">
            <%= form_for @wiki do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
                </div>
                <div class="form-group">
                    <%= f.label :body %>
                    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
                </div>
                <div class="form-group">
                    <%= f.label :private, class: 'checkbox' do %>
                        <%= f.check_box :private %> Private wiki
                    <% end %>
                </div>
                <div class="form-group">
                        <%= f.submit "Save", class: 'btn btn-success' %>
                </div>
            <% end %>
        </div>
    </div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>
<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
   <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>